name: Applications in Nodejs
on: push
jobs:
    Deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout GitHub Code to Image
              uses: actions/checkout@v3
            - name: Install Dependence
              run: npm ci
            - name: start lint
              run: npm run lint
    lintstart:
        needs: Deployment
        runs-on: ubuntu-latest
        steps:
            - name: Checkout git hub code
              uses: actions/checkout@v3
            - name: Install Dependancies
              run: npm ci
            - name: start build
              run: npm run build
    testing:
        needs: lintstart
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: Install Depend...
              run: npm ci
            - name: testing code
              run: npm run test    

