name: MyFirstWorkFlow
on: push
jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: FirstScript
          uses: actions/checkout@v3
        - name: SecondScript
          run: echo "It is working"
        - name: Npm Instllation
          run: rpm ci